#!/usr/bin/env bash

set -e

rm -rf test/tls
mkdir -p test/tls
touch test/tls/index.txt
echo 00 > test/tls/serial

cat <<- EOF > test/tls/openssl.conf
[ ca ]
default_ca      = my_ca
[ my_ca ]
database        = test/tls/index.txt
serial          = test/tls/serial
new_certs_dir   = test/tls/
x509_extensions = my_cert
name_opt         = ca_default
cert_opt         = ca_default
default_md       = default
policy           = policy_match
# 'copy_extensions' will copy over SAN ("X509v3 Subject Alternative Name") from CSR
copy_extensions = copy
[ my_cert ]
basicConstraints        = CA:FALSE
nsComment               = "generated by github.com/observiq/stanza-plugins"
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid,issuer
[ policy_match ]
# ensure CSR fields match that of delivered Cert
countryName             = match
stateOrProvinceName     = match
organizationName        = match
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional
EOF

# certificate authority
openssl genrsa -out test/tls/plugins-ca.key 2048
openssl req -new -x509 -sha256 \
    -key test/tls/plugins-ca.key \
    -out test/tls/plugins-ca.crt \
    -days 10950 \
    -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=plugins/CN=plugins-ca"

# certificate
openssl genrsa -out test/tls/plugins.key 2048
openssl req -new -key test/tls/plugins.key -out test/tls/plugins.csr \
    -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=plugins/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,DNS:plugins.plugins-dev.svc.cluster.local"
openssl ca \
    -create_serial \
    -cert test/tls/plugins-ca.crt \
    -keyfile test/tls/plugins-ca.key \
    -days 9125 \
    -in test/tls/plugins.csr \
    -batch \
    -config test/tls/openssl.conf \
    -out test/tls/plugins.crt

# append ca.crt to server certificate
cat test/tls/plugins-ca.crt >> test/tls/plugins.crt    

# client cert
openssl genrsa -out test/tls/plugins-client.key 2048
openssl req -new -key test/tls/plugins-client.key -out test/tls/plugins-client.csr \
    -subj "/C=US/ST=Michigan/L=GrandRapids/O=observIQ/OU=plugins/CN=plugins-dev-client"
openssl ca \
    -create_serial \
    -cert test/tls/plugins-ca.crt \
    -keyfile test/tls/plugins-ca.key \
    -days 9125 \
    -in test/tls/plugins-client.csr \
    -batch \
    -config test/tls/openssl.conf \
    -out test/tls/plugins-client.crt

chmod 0644 test/tls/*